language: node_js
node_js:
  - 16
git:
  depth: 1
branches:
  only:
    - main
after_success:
  - yarn coveralls
deploy:
  on:
    branch: main
    tags: true
  provider: npm
  email: umutozel@gmail.com
  api_key:
    secure: QWTJIWwSfVkvH+9aVA3UKT0Vak+gTGgOY1CzOBOAH7S+O9VZtlzgVJiPth2kQFmylcMMuy5dlqaYLdBHEfFXHR/1zU3cdznZTyenYwn9UbZlJrOc/EOV2/BFmV18cAfaY6kUZUd7NVevJyPP0A95j/FxmPH4uYPOQ9hMcL7M2NCk5t+JrhlmDrqeEREWN3PMipdMwB2pem8qmfYdcQLNUhLMHffjW7STe5ksl3DqRLhL5TN18xhHUS2pFWUI81fWoq2O+oSJ8iLBiZC3waudRLwhztWhllxREnNtozfWCJkWKZgdpBWoILP/r8+cEKC2ZhwSiqf4GWzlkbMpIn30IxUDlAJFNU/AfLUfUWoOe5syk3h9w5IGNQ6OePezlXsIPZwP0aKdXrOLpwOvj1ChnM8Q+f/ua/RIiMT1WpE5MKiJi9ouO7uh7Poy7rP2bcYdfk881DKzBEBooJQ6kPj+Jto7FEbZSw3Blf/+2+19BqW+RAgdLq3RqfhAk+oRUmTn59ZBvJHL60IKqnpPLfFTARWrzqDlB+lmc8OinHD3udVk97w8e4VtPE66y9orwONcqX8olb4VRIpkagwQ76qfFhW35dpxW0cXGZmwOMo7Ptn57lfGJuV9BtM8+O1vZWB4ygqtiNRIV2LclyXOtDfD9yax9960ndUUrMahz/XessM=
